# Generated by Django 5.2.6 on 2025-09-22 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_image',
            field=models.ImageField(blank=True, default='assets/img/profiles/default-avatar.jpg', upload_to='students/'),
        ),
    ]
