# Generated by Django 5.2.6 on 2025-09-22 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='wkEk0C7wUc0Rhmjyfjcs1t5naLNyS8kZ', editable=False, max_length=32, unique=True),
        ),
    ]
